### ISSUE TITLE
Diagonal Bewegungen prüfen

### ISSUE THREAD

**Issue by hoolie** [hoolie/BaghChalPython#3]
@Frischeiwaffel 
Irgendwo muss geprüft werden ob eine diagonale Bewegung von einer bestimmten Position aus überhaupt gestattet ist. Am besten hierfür ist glaube ich die Field-Klasse geeignet.

![image](https://cloud.githubusercontent.com/assets/5992307/9304798/3d3d7b4c-44ec-11e5-9d6f-526c5d4ba749.png)
(Nummerierung von links oben mit 0 beginnend, X nach rechts und Y nach unten)
(0/0)---(0/1)---(0/2)--...
   |          |          |       ...
(1/0)---(1/1)---(1/2)--...
...         ...        ...

addiert man X und Y Koordinaten kann man überprüfen ob das Ergebnis gerade ist. Ist das der Fall, so kann von dieser Position aus diagonal gefahren werden.

Ist das soweit richtig?

**Comment by Frischeiwaffel** [comment]
Müsste stimmen ja.

**Comment by Frischeiwaffel** [comment]
Wieso findest die Field Klasse dafür am besten geeignet? Könnte man doch genausogut noch in der Figures Klasse überprüfen.

**Comment by hoolie** [comment]
Okay, du meinst in den Klassen Tiger und Sheep

**Comment by hoolie** [comment]
ja das ist auch möglich.

**Comment by hoolie** [comment]
Dann kommt es in die _set_position von Tiger und Sheep :+1:

**Comment by hoolie** [comment]
Deshalb die überprüfung am besten in der MoveFigure
